// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALX4_BZMYElTxud5PF4Wf8uc_3BfIdKak',
    appId: '1:756503101650:web:08f99dab309070df0e2d0b',
    messagingSenderId: '756503101650',
    projectId: 'lsitproject',
    authDomain: 'lsitproject.firebaseapp.com',
    storageBucket: 'lsitproject.appspot.com',
    measurementId: 'G-LYQYK08J5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmd0uPhEDRl9hDMwhmXeGxJiLGlaoYJAc',
    appId: '1:756503101650:android:e89795a921ae0f4e0e2d0b',
    messagingSenderId: '756503101650',
    projectId: 'lsitproject',
    storageBucket: 'lsitproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFOhmS8EPXpKxkF0VOoii7dnaByDVolmI',
    appId: '1:756503101650:ios:d00e3d551503176b0e2d0b',
    messagingSenderId: '756503101650',
    projectId: 'lsitproject',
    storageBucket: 'lsitproject.appspot.com',
    iosBundleId: 'com.example.listFypProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFOhmS8EPXpKxkF0VOoii7dnaByDVolmI',
    appId: '1:756503101650:ios:7ad0cc1125ab163b0e2d0b',
    messagingSenderId: '756503101650',
    projectId: 'lsitproject',
    storageBucket: 'lsitproject.appspot.com',
    iosBundleId: 'com.example.listFypProject.RunnerTests',
  );
}
